### ISSUE TITLE
FLOPs calculation

### ISSUE THREAD

**Issue by DMH517** [tngh5004/Omnistitch#3] opened 2024-08-27 13:16 UTC
Hello author, I have a question regarding the modification of the FLOPs calculation in your project. Could you please provide more specific guidance on how to implement this change? Should I be looking at the forward() method within the Model class in core/model/omnistitch.py? Thank you for your help!
<img width="416" alt="图片1" src="https://github.com/user-attachments/assets/f27423db-4e0c-455c-be54-6902e5f0a748">

**Comment by tngh5004** [comment] 2024-08-28 00:19
We recommend this setting.

```
def forward(self, img0, pyr_level=None, nr_lvl_skipped=None):
                img1 = img0.copy()
                if pyr_level is None: pyr_level = self.pyr_level
                if nr_lvl_skipped is None: nr_lvl_skipped = self.nr_lvl_skipped
```

It's safe to assume that the amount of computation, or FLOPS, in your model will be the same, even though you're using a duplicate of the image.

**Comment by DMH517** [comment] 2024-08-29 14:00
> 我们建议使用此设置。
> 
> ```
> def forward(self, img0, pyr_level=None, nr_lvl_skipped=None):
>                 img1 = img0.copy()
>                 if pyr_level is None: pyr_level = self.pyr_level
>                 if nr_lvl_skipped is None: nr_lvl_skipped = self.nr_lvl_skipped
> ```
> 
> 可以安全地假设模型中的计算量或 FLOPS 是相同的，即使您使用的是图像的副本。

**Comment by DMH517** [comment] 2024-08-29 14:03
Following your guide, I successfully got the FLOPs, but with a slight outlier from the data you provided. (I use img1 = img0.clone() instead of img1 = img0.copy() to avoid reporting the error)
![image](https://github.com/user-attachments/assets/6465d13d-0552-406f-ab9b-5e7d289a6359)

**Comment by tngh5004** [comment] 2024-08-30 00:29
> Following your guide, I successfully got the FLOPs, but with a slight outlier from the data you provided. (I use img1 = img0.clone() instead of img1 = img0.copy() to avoid reporting the error) ![image](https://private-user-images.githubusercontent.com/179601590/362719525-6465d13d-0552-406f-ab9b-5e7d289a6359.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NzgwMTMsIm5iZiI6MTcyNDk3NzcxMywicGF0aCI6Ii8xNzk2MDE1OTAvMzYyNzE5NTI1LTY0NjVkMTNkLTA1NTItNDA2Zi1hYjliLTVlN2QyODlhNjM1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQwMDI4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2M0MWNlMjgzOWEwOGJlOWNkNTlhNGY5ZjFkYWNlNTU0Y2I1NWU0ZjAwNGVkZGQ0ZGRlZWUxZDkwNmE2MTZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ok10XcmNN4pcFdDyCnFNMk81wz3GpXjMGoQ6duVR7-0)

For FLOPS, this answer might be helpful.
https://github.com/tngh5004/Omnistitch/issues/1#issuecomment-2319503544

**Comment by DMH517** [comment] 2024-08-30 10:34
I get it, thanks!

**Closed as completed** 2024-11-22 05:01 UTC
